// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDHome.Lib.Data;

#nullable disable

namespace SDHome.Lib.Data.Migrations
{
    [DbContext(typeof(SignalsDbContext))]
    partial class SignalsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDHome.Lib.Data.Entities.AutomationActionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("AutomationRuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("automation_rule_id");

                    b.Property<int?>("DelaySeconds")
                        .HasColumnType("int")
                        .HasColumnName("delay_seconds");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_id");

                    b.Property<string>("NotificationMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("notification_message");

                    b.Property<string>("NotificationTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("notification_title");

                    b.Property<string>("Property")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("property");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scene_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.Property<string>("WebhookBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("webhook_body");

                    b.Property<string>("WebhookMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("webhook_method");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id");

                    b.HasIndex("AutomationRuleId")
                        .HasDatabaseName("idx_automation_actions_rule_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("idx_automation_actions_device_id");

                    b.ToTable("automation_actions", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.AutomationConditionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AutomationRuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("automation_rule_id");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("condition_type");

                    b.Property<string>("DaysOfWeek")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("days_of_week");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_id");

                    b.Property<string>("Operator")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("operator");

                    b.Property<string>("Property")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("property");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("TimeEnd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("time_end");

                    b.Property<string>("TimeStart")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("time_start");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.Property<string>("Value2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value2");

                    b.HasKey("Id");

                    b.HasIndex("AutomationRuleId")
                        .HasDatabaseName("idx_automation_conditions_rule_id");

                    b.ToTable("automation_conditions", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.AutomationExecutionLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActionResults")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action_results");

                    b.Property<Guid>("AutomationRuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("automation_rule_id");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("executed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TriggerSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trigger_source");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_automation_logs_executed");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_automation_logs_status");

                    b.HasIndex("AutomationRuleId", "ExecutedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_automation_logs_rule_executed");

                    b.ToTable("automation_execution_logs", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.AutomationRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<string>("ConditionMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("condition_mode");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("int")
                        .HasColumnName("cooldown_seconds");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("int")
                        .HasColumnName("execution_count");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_triggered_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("TriggerMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trigger_mode");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("idx_automation_rules_enabled");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_automation_rules_name");

                    b.ToTable("automation_rules", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.AutomationTriggerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AutomationRuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("automation_rule_id");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_id");

                    b.Property<int?>("OffsetMinutes")
                        .HasColumnType("int")
                        .HasColumnName("offset_minutes");

                    b.Property<string>("Operator")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("operator");

                    b.Property<string>("Property")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("property");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("SunEvent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sun_event");

                    b.Property<string>("TimeExpression")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("time_expression");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trigger_type");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AutomationRuleId")
                        .HasDatabaseName("idx_automation_triggers_rule_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("idx_automation_triggers_device_id");

                    b.HasIndex("TriggerType")
                        .HasDatabaseName("idx_automation_triggers_type");

                    b.ToTable("automation_triggers", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.CapabilityMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("capability");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("device_type");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_system_default");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("property");

                    b.Property<string>("StateMappings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state_mappings");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Capability")
                        .HasDatabaseName("idx_capability_mappings_capability");

                    b.HasIndex("Capability", "DeviceType")
                        .HasDatabaseName("idx_capability_mappings_cap_device");

                    b.ToTable("capability_mappings", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.CustomTriggerLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("condition");

                    b.Property<Guid>("CustomTriggerRuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("custom_trigger_rule_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("FiredUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("fired_utc");

                    b.Property<Guid?>("GeneratedTriggerEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("generated_trigger_event_id");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("metric");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("CustomTriggerRuleId")
                        .HasDatabaseName("idx_custom_trigger_logs_rule_id");

                    b.HasIndex("FiredUtc")
                        .HasDatabaseName("idx_custom_trigger_logs_fired_utc");

                    b.ToTable("custom_trigger_logs", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.CustomTriggerRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("CooldownSeconds")
                        .HasColumnType("int")
                        .HasColumnName("cooldown_seconds");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("LastFiredUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_fired_utc");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("metric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operator");

                    b.Property<double>("Threshold")
                        .HasColumnType("float")
                        .HasColumnName("threshold");

                    b.Property<double?>("Threshold2")
                        .HasColumnType("float")
                        .HasColumnName("threshold2");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trigger_type");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("idx_custom_triggers_device_id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("idx_custom_triggers_enabled");

                    b.HasIndex("Metric")
                        .HasDatabaseName("idx_custom_triggers_metric");

                    b.HasIndex("DeviceId", "Metric")
                        .HasDatabaseName("idx_custom_triggers_device_metric");

                    b.ToTable("custom_trigger_rules", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attributes");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("capabilities");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("device_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("friendly_name");

                    b.Property<string>("IeeeAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ieee_address");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("is_available");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_seen");

                    b.Property<int?>("LinkQuality")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("model_id");

                    b.Property<bool>("PowerSource")
                        .HasColumnType("bit")
                        .HasColumnName("power_source");

                    b.Property<string>("Room")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("room");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceType")
                        .HasDatabaseName("idx_devices_device_type");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("idx_devices_is_available");

                    b.HasIndex("Room")
                        .HasDatabaseName("idx_devices_room");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("idx_devices_zone_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.SceneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DeviceStates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_states");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_scenes_name");

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.SensorReadingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device_id");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("metric");

                    b.Property<Guid>("SignalEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("signal_event_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Metric", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sensor_readings_metric_ts");

                    b.HasIndex("DeviceId", "Metric", "TimestampUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_sensor_readings_device_metric_ts");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.SignalEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("capability");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("device_kind");

                    b.Property<string>("EventCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event_category");

                    b.Property<string>("EventSubType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("event_sub_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_payload");

                    b.Property<string>("RawTopic")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("raw_topic");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("source");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("timestamp_utc");

                    b.Property<double?>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_signal_events_timestamp");

                    b.HasIndex("DeviceId", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_signal_events_device_timestamp");

                    b.ToTable("signal_events", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.TriggerEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("capability");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device_id");

                    b.Property<Guid>("SignalEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("signal_event_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("TriggerSubType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trigger_sub_type");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trigger_type");

                    b.Property<bool?>("Value")
                        .HasColumnType("bit")
                        .HasColumnName("value_bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trigger_events_device_timestamp");

                    b.HasIndex("TriggerType", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trigger_events_type_timestamp");

                    b.ToTable("trigger_events", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.ZoneCapabilityAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("capability");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("display_name");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("Property")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("property");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("Capability")
                        .HasDatabaseName("idx_zone_capability_assignments_capability");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("idx_zone_capability_assignments_device_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("idx_zone_capability_assignments_zone_id");

                    b.HasIndex("ZoneId", "Capability", "Priority")
                        .IsUnique()
                        .HasDatabaseName("idx_zone_capability_assignments_unique");

                    b.ToTable("zone_capability_assignments", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.ZoneEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentZoneId")
                        .HasColumnType("int")
                        .HasColumnName("parent_zone_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_zones_name");

                    b.HasIndex("ParentZoneId")
                        .HasDatabaseName("idx_zones_parent_zone_id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.AutomationActionEntity", b =>
                {
                    b.HasOne("SDHome.Lib.Data.Entities.AutomationRuleEntity", "AutomationRule")
                        .WithMany("Actions")
                        .HasForeignKey("AutomationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomationRule");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.AutomationConditionEntity", b =>
                {
                    b.HasOne("SDHome.Lib.Data.Entities.AutomationRuleEntity", "AutomationRule")
                        .WithMany("Conditions")
                        .HasForeignKey("AutomationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomationRule");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.AutomationExecutionLogEntity", b =>
                {
                    b.HasOne("SDHome.Lib.Data.Entities.AutomationRuleEntity", "AutomationRule")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("AutomationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomationRule");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.AutomationTriggerEntity", b =>
                {
                    b.HasOne("SDHome.Lib.Data.Entities.AutomationRuleEntity", "AutomationRule")
                        .WithMany("Triggers")
                        .HasForeignKey("AutomationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomationRule");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.CustomTriggerLogEntity", b =>
                {
                    b.HasOne("SDHome.Lib.Data.Entities.CustomTriggerRuleEntity", "CustomTriggerRule")
                        .WithMany("Logs")
                        .HasForeignKey("CustomTriggerRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomTriggerRule");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.DeviceEntity", b =>
                {
                    b.HasOne("SDHome.Lib.Data.Entities.ZoneEntity", "Zone")
                        .WithMany("Devices")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.ZoneCapabilityAssignmentEntity", b =>
                {
                    b.HasOne("SDHome.Lib.Data.Entities.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDHome.Lib.Data.Entities.ZoneEntity", "Zone")
                        .WithMany("CapabilityAssignments")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.ZoneEntity", b =>
                {
                    b.HasOne("SDHome.Lib.Data.Entities.ZoneEntity", "ParentZone")
                        .WithMany("ChildZones")
                        .HasForeignKey("ParentZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentZone");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.AutomationRuleEntity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Conditions");

                    b.Navigation("ExecutionLogs");

                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.CustomTriggerRuleEntity", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.ZoneEntity", b =>
                {
                    b.Navigation("CapabilityAssignments");

                    b.Navigation("ChildZones");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
