// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDHome.Lib.Data;

#nullable disable

namespace SDHome.Lib.Data.Migrations
{
    [DbContext(typeof(SignalsDbContext))]
    partial class SignalsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDHome.Lib.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attributes");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("capabilities");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("device_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("friendly_name");

                    b.Property<string>("IeeeAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ieee_address");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("is_available");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_seen");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("model_id");

                    b.Property<bool>("PowerSource")
                        .HasColumnType("bit")
                        .HasColumnName("power_source");

                    b.Property<string>("Room")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("room");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceType")
                        .HasDatabaseName("idx_devices_device_type");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("idx_devices_is_available");

                    b.HasIndex("Room")
                        .HasDatabaseName("idx_devices_room");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("idx_devices_zone_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.SensorReadingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device_id");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("metric");

                    b.Property<Guid>("SignalEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("signal_event_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Metric", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sensor_readings_metric_ts");

                    b.HasIndex("DeviceId", "Metric", "TimestampUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_sensor_readings_device_metric_ts");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.SignalEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("capability");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("device_kind");

                    b.Property<string>("EventCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event_category");

                    b.Property<string>("EventSubType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("event_sub_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_payload");

                    b.Property<string>("RawTopic")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("raw_topic");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("source");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("timestamp_utc");

                    b.Property<double?>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_signal_events_timestamp");

                    b.HasIndex("DeviceId", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_signal_events_device_timestamp");

                    b.ToTable("signal_events", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.TriggerEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("capability");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device_id");

                    b.Property<Guid>("SignalEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("signal_event_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("TriggerSubType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trigger_sub_type");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trigger_type");

                    b.Property<bool?>("Value")
                        .HasColumnType("bit")
                        .HasColumnName("value_bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trigger_events_device_timestamp");

                    b.HasIndex("TriggerType", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trigger_events_type_timestamp");

                    b.ToTable("trigger_events", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.ZoneEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentZoneId")
                        .HasColumnType("int")
                        .HasColumnName("parent_zone_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_zones_name");

                    b.HasIndex("ParentZoneId")
                        .HasDatabaseName("idx_zones_parent_zone_id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.DeviceEntity", b =>
                {
                    b.HasOne("SDHome.Lib.Data.Entities.ZoneEntity", "Zone")
                        .WithMany("Devices")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.ZoneEntity", b =>
                {
                    b.HasOne("SDHome.Lib.Data.Entities.ZoneEntity", "ParentZone")
                        .WithMany("ChildZones")
                        .HasForeignKey("ParentZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentZone");
                });

            modelBuilder.Entity("SDHome.Lib.Data.Entities.ZoneEntity", b =>
                {
                    b.Navigation("ChildZones");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
