//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({
    providedIn: 'root'
})
export class SdHomeClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getRecentReadings(take: number | undefined): Observable<SensorReading[]> {
        let url_ = this.baseUrl + "/api/readings?";
        if (take === null)
            throw new globalThis.Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRecentReadings(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRecentReadings(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SensorReading[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SensorReading[]>;
        }));
    }

    protected processGetRecentReadings(response: HttpResponseBase): Observable<SensorReading[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SensorReading.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getReadingsForDeviceAndMetric(deviceId: string, metric: string, take: number | undefined): Observable<SensorReading[]> {
        let url_ = this.baseUrl + "/api/readings/{deviceId}/{metric}?";
        if (deviceId === undefined || deviceId === null)
            throw new globalThis.Error("The parameter 'deviceId' must be defined.");
        url_ = url_.replace("{deviceId}", encodeURIComponent("" + deviceId));
        if (metric === undefined || metric === null)
            throw new globalThis.Error("The parameter 'metric' must be defined.");
        url_ = url_.replace("{metric}", encodeURIComponent("" + metric));
        if (take === null)
            throw new globalThis.Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetReadingsForDeviceAndMetric(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetReadingsForDeviceAndMetric(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SensorReading[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SensorReading[]>;
        }));
    }

    protected processGetReadingsForDeviceAndMetric(response: HttpResponseBase): Observable<SensorReading[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SensorReading.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class SdHomeClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getSignalLogs(take: number | undefined): Observable<SignalEvent[]> {
        let url_ = this.baseUrl + "/api/signals/logs?";
        if (take === null)
            throw new globalThis.Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetSignalLogs(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetSignalLogs(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SignalEvent[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SignalEvent[]>;
        }));
    }

    protected processGetSignalLogs(response: HttpResponseBase): Observable<SignalEvent[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SignalEvent.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class SdHomeClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getRecentTriggers(take: number | undefined): Observable<TriggerEvent[]> {
        let url_ = this.baseUrl + "/api/triggers?";
        if (take === null)
            throw new globalThis.Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetRecentTriggers(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRecentTriggers(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TriggerEvent[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TriggerEvent[]>;
        }));
    }

    protected processGetRecentTriggers(response: HttpResponseBase): Observable<TriggerEvent[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TriggerEvent.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getTriggersForDevice(deviceId: string, take: number | undefined): Observable<TriggerEvent[]> {
        let url_ = this.baseUrl + "/api/triggers/{deviceId}?";
        if (deviceId === undefined || deviceId === null)
            throw new globalThis.Error("The parameter 'deviceId' must be defined.");
        url_ = url_.replace("{deviceId}", encodeURIComponent("" + deviceId));
        if (take === null)
            throw new globalThis.Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTriggersForDevice(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTriggersForDevice(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TriggerEvent[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TriggerEvent[]>;
        }));
    }

    protected processGetTriggersForDevice(response: HttpResponseBase): Observable<TriggerEvent[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TriggerEvent.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class SensorReading implements ISensorReading {
    id?: string;
    signalEventId?: string;
    timestampUtc?: Date;
    deviceId?: string;
    metric?: string;
    value?: number;
    unit?: string | undefined;

    constructor(data?: ISensorReading) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.signalEventId = _data["signalEventId"];
            this.timestampUtc = _data["timestampUtc"] ? new Date(_data["timestampUtc"].toString()) : undefined as any;
            this.deviceId = _data["deviceId"];
            this.metric = _data["metric"];
            this.value = _data["value"];
            this.unit = _data["unit"];
        }
    }

    static fromJS(data: any): SensorReading {
        data = typeof data === 'object' ? data : {};
        let result = new SensorReading();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["signalEventId"] = this.signalEventId;
        data["timestampUtc"] = this.timestampUtc ? this.timestampUtc.toISOString() : undefined as any;
        data["deviceId"] = this.deviceId;
        data["metric"] = this.metric;
        data["value"] = this.value;
        data["unit"] = this.unit;
        return data;
    }
}

export interface ISensorReading {
    id?: string;
    signalEventId?: string;
    timestampUtc?: Date;
    deviceId?: string;
    metric?: string;
    value?: number;
    unit?: string | undefined;
}

export class SignalEvent implements ISignalEvent {
    id?: string;
    source?: string;
    deviceId?: string;
    location?: string | undefined;
    capability?: string;
    eventType?: string;
    eventSubType?: string | undefined;
    value?: number | undefined;
    timestampUtc?: Date;
    rawTopic?: string;
    rawPayload?: any;
    deviceKind?: DeviceKind;
    eventCategory?: EventCategory;
    rawPayloadArray?: any | undefined;

    constructor(data?: ISignalEvent) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.source = _data["source"];
            this.deviceId = _data["deviceId"];
            this.location = _data["location"];
            this.capability = _data["capability"];
            this.eventType = _data["eventType"];
            this.eventSubType = _data["eventSubType"];
            this.value = _data["value"];
            this.timestampUtc = _data["timestampUtc"] ? new Date(_data["timestampUtc"].toString()) : undefined as any;
            this.rawTopic = _data["rawTopic"];
            this.rawPayload = _data["rawPayload"];
            this.deviceKind = _data["deviceKind"];
            this.eventCategory = _data["eventCategory"];
            this.rawPayloadArray = _data["rawPayloadArray"];
        }
    }

    static fromJS(data: any): SignalEvent {
        data = typeof data === 'object' ? data : {};
        let result = new SignalEvent();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["source"] = this.source;
        data["deviceId"] = this.deviceId;
        data["location"] = this.location;
        data["capability"] = this.capability;
        data["eventType"] = this.eventType;
        data["eventSubType"] = this.eventSubType;
        data["value"] = this.value;
        data["timestampUtc"] = this.timestampUtc ? this.timestampUtc.toISOString() : undefined as any;
        data["rawTopic"] = this.rawTopic;
        data["rawPayload"] = this.rawPayload;
        data["deviceKind"] = this.deviceKind;
        data["eventCategory"] = this.eventCategory;
        data["rawPayloadArray"] = this.rawPayloadArray;
        return data;
    }
}

export interface ISignalEvent {
    id?: string;
    source?: string;
    deviceId?: string;
    location?: string | undefined;
    capability?: string;
    eventType?: string;
    eventSubType?: string | undefined;
    value?: number | undefined;
    timestampUtc?: Date;
    rawTopic?: string;
    rawPayload?: any;
    deviceKind?: DeviceKind;
    eventCategory?: EventCategory;
    rawPayloadArray?: any | undefined;
}

export enum DeviceKind {
    Unknown = 0,
    Button = 1,
    MotionSensor = 2,
    ContactSensor = 3,
    Thermometer = 4,
    Light = 5,
    Switch = 6,
    Outlet = 7,
}

export enum EventCategory {
    Trigger = 0,
    Telemetry = 1,
}

export class TriggerEvent implements ITriggerEvent {
    id?: string;
    signalEventId?: string;
    timestampUtc?: Date;
    deviceId?: string;
    capability?: string;
    triggerType?: string;
    triggerSubType?: string | undefined;
    value?: boolean | undefined;

    constructor(data?: ITriggerEvent) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.signalEventId = _data["signalEventId"];
            this.timestampUtc = _data["timestampUtc"] ? new Date(_data["timestampUtc"].toString()) : undefined as any;
            this.deviceId = _data["deviceId"];
            this.capability = _data["capability"];
            this.triggerType = _data["triggerType"];
            this.triggerSubType = _data["triggerSubType"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): TriggerEvent {
        data = typeof data === 'object' ? data : {};
        let result = new TriggerEvent();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["signalEventId"] = this.signalEventId;
        data["timestampUtc"] = this.timestampUtc ? this.timestampUtc.toISOString() : undefined as any;
        data["deviceId"] = this.deviceId;
        data["capability"] = this.capability;
        data["triggerType"] = this.triggerType;
        data["triggerSubType"] = this.triggerSubType;
        data["value"] = this.value;
        return data;
    }
}

export interface ITriggerEvent {
    id?: string;
    signalEventId?: string;
    timestampUtc?: Date;
    deviceId?: string;
    capability?: string;
    triggerType?: string;
    triggerSubType?: string | undefined;
    value?: boolean | undefined;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}